cacheUrl: ""

deployment:
  image:
    repository: ghcr.io/commune-ai/commune-cache

  resources:
    limits:
      memory: 512Mi
      cpu: 1
    requests:
      memory: 200Mi
      cpu: 0.1

  command: ["pnpm"]
  args: ["tsx", "./src/index.ts"]

  startupProbe:
    httpGet:
      path: /api/stake-out

  readinessProbe:
    periodSeconds: 30
    timeoutSeconds: 3
    httpGet:
      path: /api/stake-out

  livenessProbe:
    periodSeconds: 30
    timeoutSeconds: 3
    httpGet:
      path: /api/stake-out
